### ISSUE TITLE
Cannot update schedule for route management

### ISSUE THREAD

**Issue by NEWLY2014** [ZoeBijl/airlinesim-enhancement-suite#16] opened 2024-05-11 19:46 UTC
After clicking "extract schedule data" under the "General" section, it jumps to the schedule interface and displays "Schedule extracted!". However, new routes will not appear under the "Route Management" section.

Version: 0.6.7
Browser: Chrome 123.0.6312.106 (x64)

**Comment by ZoeBijl** [comment] 2024-05-15 08:11
Thank you for the report, I’ll see if I can replicate this :)

**Comment by ZoeBijl** [comment] 2024-05-20 03:21
I have been able to reproduce

**Comment by ZoeBijl** [comment] 2024-05-23 10:24
As far as I can tell this is due to the lack of data sanitation. I’ve added a fix in the development branch. Will release with some other updates soon.

**Comment by ZoeBijl** [comment] 2024-06-05 23:31
@NEWLY2014 I’ve published a fix in the development branch. Would you be able to test if that fixes your issue?

**Comment by ZoeBijl** [comment] 2024-06-07 18:05
I’m closing this as the issue is fixed for me. Feel free to re-open if it persists for you!

**Closed by ZoeBijl** 2024-06-07 18:05 UTC
Labels: bug
